CSOURCES=romain.c
PROGRAMS=romain
romain_OBJECTS=romain.o
romain_LIBRARIES=

include $(MAKEDIR)/common
-include Makefile.depend

#### Makefile                         -- 2003-12-02 12:48:39 -- pascal   ####
