#******************************************************************************
#FILE:              makefile
#LANGUAGE:          make
#SYSTEM:            UNIX
#USER-INTERFACE:    None
#DESCRIPTION
#   This is the makefile for cplusinherited.
#
#AUTHORS
#   <PJB> Pascal J. Bourguignon
#MODIFICATIONS
#   1999-06-05 <PJB> Added this comment.
#LEGAL
#    GPL
#    
#    Copyright Pascal Bourguignon 1993 - 1999
#    
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the GNU General Public License
#    as published by the Free Software Foundation; either version
#    2 of the License, or (at your option) any later version.
#    
#    This program is distributed in the hope that it will be
#    useful, but WITHOUT ANY WARRANTY; without even the implied
#    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
#    PURPOSE.  See the GNU General Public License for more details.
#    
#    You should have received a copy of the GNU General Public
#    License along with this program; if not, write to the Free
#    Software Foundation, Inc., 59 Temple Place, Suite 330,
#    Boston, MA 02111-1307 USA
#******************************************************************************
CSOURCES=cplusinherited.c
PROGRAMS=cplusinherited
cplusinherited_OBJECTS=$(CSOURCES:.c=.o)
cplusinherited_LIBRARIES=

include $(MAKEDIR)/common
-include Makefile.depend

#### Makefile                         -- 2003-12-02 12:44:50 -- pascal   ####
