.TH text 1 local
.SH NAME
text \- filters out non-ascii characters.
.SH SYNOPSIS
.B text
<
.I input 
>
.I output
.SH DESCRIPTION
.I text
is a filter used to remove all bytes other than 
.B printable 
ASCII or newline or tabulation.
.SH FILES
none.
.SH SEE ALSO
.IR sevenbit (1)
.br
.SH DIAGNOSTICS
none.
.SH AUTHOR
Pascal J. Bourguignon
... ha!


