CSOURCES=geturls.c
PROGRAMS=geturls
geturls_OBJECTS=geturls.o
geturls_LIBRARIES=

include $(MAKEDIR)/common
-include Makefile.depend
#### Makefile                         -- 2003-12-02 12:52:23 -- pascal   ####
