#******************************************************************************
#FILE:				makefile
#LANGUAGE:			make
#SYSTEM:			UNIX
#USER-INTERFACE:	None
#DESCRIPTION
#	This is the makefile for the newmoon tool.
#AUTHORS
#MODIFICATIONS
#	1994-03-16 <PJB> Added clean and clean-all targets.
#LEGAL
#    Public Domain
#    
#    This software is in Public Domain.
#    You're free to do with it as you please.
#******************************************************************************
CSOURCES=newmoon.c
PROGRAMS=newmoon
newmoon_OBJECTS=newmoon.o
newmoon_LIBRARIES= -lncurses

include $(MAKEDIR)/common
-include Makefile.depend


#### Makefile                         -- 2003-12-02 13:12:26 -- pascal   ####
