#******************************************************************************
#FILE:				makefile
#LANGUAGE:			make
#SYSTEM:			UNIX
#USER-INTERFACE:	None
#DESCRIPTION
#	This is the makefile for low-bit extracter.
#AUTHORS
#	<PJB> Pascal J. Bourguignon
#MODIFICATIONS
#	1999/06/05 <PJB> Creation.
#	Revision 1.1  2003/12/04 03:46:06  pjbpjb
#	Cleaned-up.
#	Fix.
#	
#LEGAL
#	Copyright Pascal J. Bourguignon 1994 - 1994
#	All rights reserved.
#	This program or any part of it may not be included in any commercial 
#	product without the author written permission. It may be used freely for 
#	any non-commercial purpose, provided that this header is always included.
#******************************************************************************

CSOURCES = extractbit1.c
PROGRAMS = extractbit1
extractbit1_OBJECTS = extractbit1.o

include $(MAKEDIR)/common
-include Makefile.depend

#### Makefile                         --                     --          ####
