
INCLUDES=-I.
CSOURCES = odhv2hex.c postodax.c
PROGRAMS = odhv2hex postodax
odhv2hex_OBJECTS = odhv2hex.o
postodax_OBJECTS = postodax.o
MANPAGES = odhv2hex.1 postodax.1

include $(MAKEDIR)/common
-include Makefile.depend

#### Makefile                         -- 2003-12-02 13:06:55 -- pascal   ####
