CSOURCES=MacBinary.c mb2t.c
INCLUDES=-I. -I$(PREFIX)/lib/bclib/interfaces
PROGRAMS=mb2t
mb2t_OBJECTS=MacBinary.o mb2t.o
mb2t_LIBRARIES=$(PREFIX)/lib/bclib/libraries/libbclib.a

include $(MAKEDIR)/common
-include Makefile.depend

#### Makefile                         -- 2003-12-02 13:15:29 -- pascal   ####
