CPLUSSOURCES=random-stat.cc
PROGRAMS=random-stat
random-stat_OBJECTS=random-stat.o
random-stat_LIBRARIES=
random-stat_LD=$(CCPLUS)

include $(MAKEDIR)/common
-include Makefile.depend

#### Makefile                         -- 2003-12-02 12:46:54 -- pascal   ####
