TARGET  := $(shell uname)
PREFIX  := /usr/local
MAKEDIR := $(shell pwd)/../../common/makedir

MODULE=ascii-utilities
include $(MAKEDIR)/module


#### Makefile                         --                     --          ####
