MAKEDIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../common/makedir)
MODULE=extractbit1
include $(MAKEDIR)/module

#### Makefile                         -- 2003-12-02 13:10:45 -- pascal   ####
