CSOURCES = truncate.c binskip.c
PROGRAMS = truncate binskip
truncate_OBJECTS = truncate.o
binskip_OBJECTS = binskip.o
include $(MAKEDIR)/common
-include Makefile.depend
#### Makefile                         -- 2003-12-02 13:03:31 -- pascal   ####
