MAKEDIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../common/makedir)
MODULES=\
	binhexlib \
	binhextools \
	macbinary \
	single_to_double 

include $(MAKEDIR)/project

#### Makefile                         -- 2003-12-02 15:14:40 -- pascal   ####
