
CSOURCES=sumascii.c
PROGRAMS=sumascii
sumascii_OBJECTS=$(CSOURCES:.c=.o)
sumascii_LIBRARIES=

include $(MAKEDIR)/common
-include Makefile.depend

#### Makefile                         -- 2003-12-02 12:44:15 -- pascal   ####
