MAKEDIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../common/makedir)
MODULE=random-stat
include $(MAKEDIR)/module

#### Makefile                         -- 2003-12-02 12:47:06 -- pascal   ####
