MAKEDIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../common/makedir)
MODULE=objc-tools
include $(MAKEDIR)/module

#### Makefile                         -- 2003-12-02 12:58:13 -- pascal   ####
