MAKEDIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../common/makedir)
MODULE=cplusinherited
include $(MAKEDIR)/module
#### Makefile                         -- 2003-12-02 12:44:54 -- pascal   ####
