CSOURCES=make-person-aliases.c
PROGRAMS=make-person-aliases
make-person-aliases_OBJECTS=make-person-aliases.o
include $(MAKEDIR)/common
-include Makefile.depend
#### Makefile                         -- 2003-12-02 13:11:42 -- pascal   ####
